name: "Build and Deploy"

on:
  push:
    branches: [ main ]

env:
  PACKAGE_PATH: './published'

jobs:
  builds:
    name: Build and Deploy
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup dotnet ${{ vars.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ vars.DOTNET_VERSION }}

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Package
      run: dotnet publish --no-build -c Release --property:PublishDir=${{ env.PACKAGE_PATH }}

    - name: Deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ vars.AZURE_APP_SERVICE_NAME }}
        publish-profile: $${ secrets.AZURE_APP_SERVICE_PUBLISH_SETTINGS }}
        package: ${{ env.PACKAGE_PATH }}

