name: "Build and Deploy"

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/*'
      - '.github/ISSUE_TEMPLATE/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/*'
      - '.github/ISSUE_TEMPLATE/**'

env:
  APP_SERVICE_PROJECT: 'SampleAppService'

jobs:
  builds:
    name: Build and Deploy
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet ${{ vars.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ vars.DOTNET_VERSION }}

      - name: Get git short hash
        id: git_short_hash
        run: echo "::set-output name=result::$(git rev-parse --short "${{ github.sha }}")"

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Package
        run: dotnet publish --no-build -c Release -o ./publish ${{ env.APP_SERVICE_PROJECT }}

      - name: Upload ${{ env.APP_SERVICE_PROJECT }} Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.APP_SERVICE_PROJECT }}-${{ steps.git_short_hash.outputs.result}}
          path: publish
