name: deploy-command
on:
  repository_dispatch:
    types: [deploy-command]
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Get vars
        id: vars
        run: |
          $version="${{ github.event.client_payload.slash_command.args.named.version }}"
          $env="${{ github.event.client_payload.slash_command.args.named.env }}"
          if ([string]::IsNullOrEmpty($version)) { echo "Missing version arg"; exit 1; }
          if ([string]::IsNullOrEmpty($env)) { echo "Missing env arg"; exit 1; }
          echo "version=$version" >> $env:GITHUB_OUTPUT
          echo "env=$env" >> $env:GITHUB_OUTPUT

      - name: Download ${{ vars.APP_SERVICE_PROJECT }} Artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ vars.APP_SERVICE_PROJECT }}-${{ steps.vars.outputs.version }}
          path: ${{ vars.APP_SERVICE_PROJECT }}-${{ steps.vars.outputs.version }}

      - name: Deploy ${{ vars.APP_SERVICE_PROJECT }}
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.AZURE_APP_SERVICE_NAME }}
          publish-profile: ${{ secrets.AZURE_APP_SERVICE_PUBLISH_SETTINGS }}
          package: ${{ vars.APP_SERVICE_PROJECT }}-${{ steps.vars.outputs.version }}

      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.event.client_payload.github.payload.repository.full_name }}
          comment-id: ${{ github.event.client_payload.github.payload.comment.id }}
          reaction-type: hooray
